const fs = require('fs');
const path = require('path');

const n5BunpoData = [
  {"id":1,"pattern":"～は～です (wa... desu)","arti":"Adalah (Penanda Subjek)","penjelasan":"Pola kalimat paling dasar dalam bahasa Jepang. 'は' (dibaca wa) menandakan subjek, dan 'です' digunakan sebagai predikat penegas (adalah).","contoh":[{"jp":"わたしはがくせいです。","id":"Watashi wa gakusei desu.","id_arti":"Saya adalah seorang siswa."},{"jp":"かれはせんせいです。","id":"Kare wa sensei desu.","id_arti":"Dia (laki-laki) adalah seorang guru."}]},
  {"id":2,"pattern":"～は～ではありません","arti":"Bukan (Bentuk Negatif)","penjelasan":"Bentuk negatif dari です. Digunakan untuk menyangkal identitas atau keadaan.","contoh":[{"jp":"わたしはせんせいではありません。","id":"Watashi wa sensei dewa arimasen.","id_arti":"Saya bukan seorang guru."}]},
  {"id":3,"pattern":"～か (ka)","arti":"Apakah (Partikel Tanya)","penjelasan":"Menambahkan 'か' di akhir kalimat menjadikannya kalimat tanya.","contoh":[{"jp":"あなたはがくせいですか。","id":"Anata wa gakusei desu ka.","id_arti":"Apakah kamu seorang siswa?"}]},
  {"id":4,"pattern":"～の (no)","arti":"Milik (Partikel Kepemilikan)","penjelasan":"Partikel 'の' menggabungkan dua kata benda, biasanya berarti kepemilikan.","contoh":[{"jp":"これはわたしのほんです。","id":"Kore wa watashi no hon desu.","id_arti":"Ini adalah buku milik saya."}]},
  {"id":5,"pattern":"～も (mo)","arti":"Juga","penjelasan":"Partikel 'も' menggantikan 'は' untuk menyatakan 'juga' atau kesamaan.","contoh":[{"jp":"わたしもがくせいです。","id":"Watashi mo gakusei desu.","id_arti":"Saya juga seorang siswa."}]},
  {"id":6,"pattern":"これ / それ / あれ","arti":"Ini / Itu / Itu (Jauh)","penjelasan":"Kata ganti penunjuk benda. Kore (dekat pembicara), Sore (dekat lawan bicara), Are (jauh dari keduanya).","contoh":[{"jp":"それはなんですか。","id":"Sore wa nan desu ka.","id_arti":"Itu apa?"}]},
  {"id":7,"pattern":"この / その / あの","arti":"~ Ini / ~ Itu","penjelasan":"Kata penunjuk benda yang harus diikuti langsung oleh Kata Benda.","contoh":[{"jp":"このほんはわたしのです。","id":"Kono hon wa watashi no desu.","id_arti":"Buku ini milik saya."}]},
  {"id":8,"pattern":"ここ / そこ / あそこ","arti":"Di sini / Di sana / Di sana (Jauh)","penjelasan":"Kata penunjuk tempat.","contoh":[{"jp":"トイレはあそこです。","id":"Toire wa asoko desu.","id_arti":"Toilet ada di sana."}]},
  {"id":9,"pattern":"～に～があります/います","arti":"Di ~ ada ~","penjelasan":"Menunjukkan keberadaan. 'Arimasu' untuk benda mati/tanaman. 'Imasu' untuk makhluk hidup.","contoh":[{"jp":"つくえのうえにほんがあります。","id":"Tsukue no ue ni hon ga arimasu.","id_arti":"Di atas meja ada buku."},{"jp":"にわにいぬがいます。","id":"Niwa ni inu ga imasu.","id_arti":"Di taman ada anjing."}]},
  {"id":10,"pattern":"～を (wo/o)","arti":"Partikel Objek","penjelasan":"Menunjukkan objek dari kata kerja transitif.","contoh":[{"jp":"ごはんをたべます。","id":"Gohan o tabemasu.","id_arti":"Makan nasi."}]},
  {"id":11,"pattern":"～へ (e)","arti":"Partikel Arah","penjelasan":"Menunjukkan arah pergerakan. Ditulis dengan hiragana 'he' tapi dibaca 'e'.","contoh":[{"jp":"がっこうへいきます。","id":"Gakkou e ikimasu.","id_arti":"Pergi ke sekolah."}]},
  {"id":12,"pattern":"～で (de)","arti":"Di / Menggunakan (Metode)","penjelasan":"Menunjukkan tempat terjadinya aksi, atau alat/metode yang digunakan.","contoh":[{"jp":"バスでいきます。","id":"Basu de ikimasu.","id_arti":"Pergi menggunakan bus."},{"jp":"レストランでごはんをたべます。","id":"Resutoran de gohan o tabemasu.","id_arti":"Makan nasi di restoran."}]},
  {"id":13,"pattern":"～と (to)","arti":"Dan / Bersama","penjelasan":"Menggabungkan kata benda atau menyatakan penyertaan.","contoh":[{"jp":"ほんとペン","id":"Hon to pen.","id_arti":"Buku dan pena."},{"jp":"ともだちといきます。","id":"Tomodachi to ikimasu.","id_arti":"Pergi bersama teman."}]},
  {"id":14,"pattern":"～ませんか","arti":"Maukah / Tidakkah (Ajakan)","penjelasan":"Bentuk tanya negatif dari kata kerja yang digunakan untuk mengajak dengan sopan.","contoh":[{"jp":"いっしょにえいがをみませんか。","id":"Issho ni eiga o mimasen ka.","id_arti":"Maukah menonton film bersama?"}]},
  {"id":15,"pattern":"～ましょう","arti":"Mari kita ~","penjelasan":"Digunakan untuk mengajak atau menawarkan sesuatu bersama-sama.","contoh":[{"jp":"いきましょう。","id":"Ikimashou.","id_arti":"Mari kita pergi."}]},
  {"id":16,"pattern":"～たい (tai)","arti":"Ingin ~","penjelasan":"Menyatakan keinginan untuk melakukan suatu aksi. Ditambahkan pada bentuk masu-stem.","contoh":[{"jp":"みずをのみたいです。","id":"Mizu o nomitai desu.","id_arti":"Saya ingin minum air."}]},
  {"id":17,"pattern":"～て (Te-form)","arti":"Bentuk -te","penjelasan":"Bentuk sambung kata kerja. Digunakan untuk merangkai aksi atau perintah halus.","contoh":[{"jp":"これをみてください。","id":"Kore o mite kudasai.","id_arti":"Tolong lihat ini."}]},
  {"id":18,"pattern":"～ています (te imasu)","arti":"Sedang ~","penjelasan":"Menyatakan aksi yang sedang berlangsung (present continuous) atau suatu status/keadaan.","contoh":[{"jp":"いま、ほんをよんでいます。","id":"Ima, hon o yonde imasu.","id_arti":"Sekarang sedang membaca buku."}]},
  {"id":19,"pattern":"～てもいいですか","arti":"Bolehkah saya ~ ?","penjelasan":"Digunakan untuk meminta izin.","contoh":[{"jp":"しゃしんをとってもいいですか。","id":"Shashin o totte mo ii desu ka.","id_arti":"Bolehkah saya mengambil foto?"}]},
  {"id":20,"pattern":"～てはいけません","arti":"Tidak boleh ~","penjelasan":"Digunakan untuk melarang (larangan keras).","contoh":[{"jp":"ここでタバコをすってはいけません。","id":"Koko de tabako o sutte wa ikemasen.","id_arti":"Tidak boleh merokok di sini."}]},
  {"id":21,"pattern":"～から / ～まで","arti":"Dari ~ / Sampai ~","penjelasan":"Menunjukkan titik awal dan titik akhir waktu atau tempat.","contoh":[{"jp":"９じから５じまで。","id":"Kuji kara goji made.","id_arti":"Dari jam 9 sampai jam 5."}]},
  {"id":22,"pattern":"～がすきです","arti":"Suka ~","penjelasan":"Menyatakan kesukaan terhadap suatu objek. Menggunakan partikel が.","contoh":[{"jp":"わたしはねこがすきです。","id":"Watashi wa neko ga suki desu.","id_arti":"Saya suka kucing."}]},
  {"id":23,"pattern":"～がじょうずです","arti":"Pintar / Ahli dalam ~","penjelasan":"Menyatakan keahlian diri sendiri atau orang lain.","contoh":[{"jp":"かれはにほんごがじょうずです。","id":"Kare wa nihongo ga jouzu desu.","id_arti":"Dia pintar bahasa Jepang."}]},
  {"id":24,"pattern":"～ないでください","arti":"Tolong jangan ~","penjelasan":"Meminta seseorang untuk tidak melakukan sesuatu.","contoh":[{"jp":"わすれないでください。","id":"Wasurenai de kudasai.","id_arti":"Tolong jangan lupa."}]},
  {"id":25,"pattern":"～のがすきです","arti":"Suka melakukan ~","penjelasan":"Menjadikan kata kerja sebagai kata benda (nominalisasi) untuk menyatakan suka pada suatu aktivitas.","contoh":[{"jp":"ほんをよむのがすきです。","id":"Hon o yomu no ga suki desu.","id_arti":"Suka membaca buku."}]}
];

fs.writeFileSync(path.join(__dirname, 'src', 'data', 'bunpoN5.json'), JSON.stringify(n5BunpoData, null, 2));
console.log('bunpoN5.json updated with ' + n5BunpoData.length + ' grammar points.');

const n4BunpoData = [
  {"id":1,"pattern":"～ことができます","arti":"Bisa ~","penjelasan":"Menyatakan kesanggupan atau kemampuan melakukan sesuatu. Diikuti kata kerja bentuk kamus.","contoh":[{"jp":"にほんごをはなすことができます。","id":"Nihongo o hanasu koto ga dekimasu.","id_arti":"(Saya) bisa berbicara bahasa Jepang."}]},
  {"id":2,"pattern":"～たことがあります","arti":"Pernah ~","penjelasan":"Menyatakan pengalaman di masa lampau. Menggunakan kata kerja bentuk lampau -ta.","contoh":[{"jp":"にほんへいったことがあります。","id":"Nihon e itta koto ga arimasu.","id_arti":"(Saya) pernah pergi ke Jepang."}]},
  {"id":3,"pattern":"～たり、～たりします","arti":"Melakukan ~ dan ~ (di antara aktivitas lain)","penjelasan":"Mendaftar contoh aksi yang tidak berurutan dan bukan merupakan daftar lengkap.","contoh":[{"jp":"えいがをみたり、ほんをよんだりします。","id":"Eiga o mitari, hon o yondari shimasu.","id_arti":"(Saya) kadang menonton film, kadang membaca buku."}]},
  {"id":4,"pattern":"～ほうがいいです","arti":"Sebaiknya ~","penjelasan":"Memberikan saran atau nasihat.","contoh":[{"jp":"くすりをのんだほうがいいですよ。","id":"Kusuri o nonda hou ga ii desu yo.","id_arti":"Sebaiknya Anda meminum obat."}]},
  {"id":5,"pattern":"～つもりです","arti":"Bermaksud untuk ~","penjelasan":"Menyatakan niat atau rencana pasti.","contoh":[{"jp":"あした、かいものにいくつもりです。","id":"Ashita, kaimono ni iku tsumori desu.","id_arti":"Saya bermaksud pergi belanja besok."}]},
  {"id":6,"pattern":"～でしょう","arti":"Mungkin / ~kan?","penjelasan":"Menyatakan dugaan halus atau meminta persetujuan.","contoh":[{"jp":"あしたはあめがふるでしょう。","id":"Ashita wa ame ga furu deshou.","id_arti":"Mungkin besok akan hujan."}]},
  {"id":7,"pattern":"～かもしれません","arti":"Mungkin saja ~","penjelasan":"Menyatakan probabilitas yang lebih rendah (sekitar 50%).","contoh":[{"jp":"かれはこないかもしれません。","id":"Kare wa konai kamoshiremasen.","id_arti":"Mungkin saja dia tidak datang."}]},
  {"id":8,"pattern":"～なければなりません","arti":"Harus ~","penjelasan":"Menyatakan kewajiban keras. Berasal dari 'kalau tidak ~ maka tidak boleh'.","contoh":[{"jp":"しゅくだいをしなければなりません。","id":"Shukudai o shinakereba narimasen.","id_arti":"(Saya) harus mengerjakan PR."}]},
  {"id":9,"pattern":"～なくてもいいです","arti":"Tidak usah / Tidak perlu ~","penjelasan":"Menyatakan bahwa suatu tindakan tidak wajib dilakukan.","contoh":[{"jp":"あしたはこなくてもいいです。","id":"Ashita wa konakutemo ii desu.","id_arti":"Besok Anda tidak perlu datang."}]},
  {"id":10,"pattern":"～てから","arti":"Setelah ~","penjelasan":"Menekankan bahwa aksi kedua terjadi SETELAH aksi pertama selesai.","contoh":[{"jp":"てをあらってから、ごはんをたべます。","id":"Te o aratte kara, gohan o tabemasu.","id_arti":"Setelah mencuci tangan, (saya) makan nasi."}]},
  {"id":11,"pattern":"～ば (Bentuk Pengandaian)","arti":"Jika / Kalau ~","penjelasan":"Syarat logis. Jika A terjadi, maka B pasti terjadi.","contoh":[{"jp":"はるになれば、さくらがさきます。","id":"Haru ni nareba, sakura ga sakimasu.","id_arti":"Jika musim semi tiba, bunga sakura mekar."}]},
  {"id":12,"pattern":"～なら","arti":"Jika (Kontekstual)","penjelasan":"Memberikan syarat atau menyarankan berdasarkan topik yang diangkat.","contoh":[{"jp":"にほんへいくなら、きょうとがいいですよ。","id":"Nihon e iku nara, Kyouto ga ii desu yo.","id_arti":"Jika (kamu bilang) pergi ke Jepang, Kyoto itu bagus lho."}]},
  {"id":13,"pattern":"～てしまう","arti":"Telah (menyesal / tuntas)","penjelasan":"Menyatakan aksi telah selesai (biasanya dengan kesan penyesalan).","contoh":[{"jp":"パスポートをわすれてしまいました。","id":"Pasupooto o wasurete shimaimashita.","id_arti":"(Gawat), saya lupa bawa paspor."}]},
  {"id":14,"pattern":"～ておく","arti":"Melakukan sesuatu sebagai persiapan","penjelasan":"Tindakan yang dilakukan terlebih dahulu untuk keperluan nanti.","contoh":[{"jp":"ホテルをよやくしておきます。","id":"Hoteru o yoyaku shite okimasu.","id_arti":"(Saya) mem-booking hotel (sebagai persiapan)."}]},
  {"id":15,"pattern":"～てある","arti":"Telah di~ (Status)","penjelasan":"Menyatakan hasil dari sebuah tindakan disengaja yang statusnya masih tersisa (Transitif).","contoh":[{"jp":"ドアがあけてあります。","id":"Doa ga akete arimasu.","id_arti":"Pintu telah (sengaja) dibuka."}]},
  {"id":16,"pattern":"～てみる","arti":"Mencoba ~","penjelasan":"Mencoba melakukan sesuatu untuk melihat bagaimana hasilnya.","contoh":[{"jp":"このくつをはいてみてもいいですか。","id":"Kono kutsu o haite mite mo ii desu ka.","id_arti":"Bolehkah saya mencoba memakai sepatu ini?"}]},
  {"id":17,"pattern":"～すぎる","arti":"Terlalu ~","penjelasan":"Menyatakan kelebihan (biasanya berkonotasi negatif).","contoh":[{"jp":"このラーメンはからすぎます。","id":"Kono raamen wa karasugimasu.","id_arti":"Ramen ini terlalu pedas."}]},
  {"id":18,"pattern":"～やすい / ～にくい","arti":"Mudah di~ / Sulit di~","penjelasan":"Menyatakan tingkat kesulitan suatu tindakan.","contoh":[{"jp":"このほんはよみやすいです。","id":"Kono hon wa yomiyasui desu.","id_arti":"Buku ini mudah dibaca."}]},
  {"id":19,"pattern":"～そうです (Dugaan Visual)","arti":"Kelihatannya ~","penjelasan":"Dugaan berdasarkan apa yang terlihat oleh mata pada saat itu.","contoh":[{"jp":"あめがふりそうです。","id":"Ame ga furisou desu.","id_arti":"Kelihatannya mau hujan."}]},
  {"id":20,"pattern":"～そうです (Kabar Hearsay)","arti":"Katanya ~ / Kudengar ~","penjelasan":"Menyampaikan kembali informasi yang didapat dari pihak lain. Disambung dengan bentuk biasa.","contoh":[{"jp":"あしたはあめがふるそうです。","id":"Ashita wa ame ga furu sou desu.","id_arti":"Katanya besok akan hujan."}]},
  {"id":21,"pattern":"～ようにする","arti":"Berusaha untuk ~","penjelasan":"Menyatakan niat atau rutinitas untuk mencoba mencapai suatu kebiasaan.","contoh":[{"jp":"まいにちうんどうするようにしています。","id":"Mainichi undou suru you ni shite imasu.","id_arti":"(Saya) berusaha olahraga setiap hari."}]},
  {"id":22,"pattern":"～ようになる","arti":"Menjadi bisa ~","penjelasan":"Perubahan status dari tidak bisa menjadi bisa.","contoh":[{"jp":"にほんごがはなせるようになりました。","id":"Nihongo ga hanaseru you ni narimashita.","id_arti":"Saya menjadi bisa berbicara bahasa Jepang."}]},
  {"id":23,"pattern":"～ために","arti":"Demi / Untuk ~","penjelasan":"Menyatakan tujuan secara konkret dan kuat.","contoh":[{"jp":"けんこうのために、やさいをたべます。","id":"Kenkou no tame ni, yasai o tabemasu.","id_arti":"Demi kesehatan, saya makan sayur."}]},
  {"id":24,"pattern":"～のに","arti":"Meskipun ~","penjelasan":"Menyatakan kekecewaan atau keterkejutan karena bertentangan dengan ekspektasi.","contoh":[{"jp":"たくさんべんきょうしたのに、テストがだめでした。","id":"Takusan benkyou shita noni, tesuto ga dame deshita.","id_arti":"Meskipun sudah belajar banyak, ulangannya jelek."}]},
  {"id":25,"pattern":"～という (To iu)","arti":"Yang bernama ~","penjelasan":"Digunakan untuk mendeskripsikan atau memperkenalkan kata benda.","contoh":[{"jp":"これはドラえもんというアニメです。","id":"Kore wa Doraemon to iu anime desu.","id_arti":"Ini adalah anime yang bernama Doraemon."}]}
];

fs.writeFileSync(path.join(__dirname, 'src', 'data', 'bunpoN4.json'), JSON.stringify(n4BunpoData, null, 2));
console.log('bunpoN4.json updated with ' + n4BunpoData.length + ' grammar points.');
